/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as MeetingsIndexRouteImport } from './routes/meetings.index'
import { Route as MeetingsIdRouteImport } from './routes/meetings.$id'
import { Route as MeetingsNewRouteImport } from './routes/meetings.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsIndexRoute = MeetingsIndexRouteImport.update({
  id: '/meetings/',
  path: '/meetings/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsIdRoute = MeetingsIdRouteImport.update({
  id: '/meetings/$id',
  path: '/meetings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsNewRoute = MeetingsNewRouteImport.update({
  id: '/meetings/new',
  path: '/meetings/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/tasks': typeof TasksRoute
  '/meetings/$id': typeof MeetingsIdRoute
  '/meetings/new': typeof MeetingsNewRoute
  '/meetings/': typeof MeetingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/tasks': typeof TasksRoute
  '/meetings/$id': typeof MeetingsIdRoute
  '/meetings/new': typeof MeetingsNewRoute
  '/meetings': typeof MeetingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/tasks': typeof TasksRoute
  '/meetings/$id': typeof MeetingsIdRoute
  '/meetings/new': typeof MeetingsNewRoute
  '/meetings/': typeof MeetingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/notifications'
    | '/profile'
    | '/tasks'
    | '/meetings/$id'
    | '/meetings/new'
    | '/meetings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/notifications'
    | '/profile'
    | '/tasks'
    | '/meetings/$id'
    | '/meetings/new'
    | '/meetings'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/notifications'
    | '/profile'
    | '/tasks'
    | '/meetings/$id'
    | '/meetings/new'
    | '/meetings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  TasksRoute: typeof TasksRoute
  MeetingsIdRoute: typeof MeetingsIdRoute
  MeetingsNewRoute: typeof MeetingsNewRoute
  MeetingsIndexRoute: typeof MeetingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings/': {
      id: '/meetings/'
      path: '/meetings'
      fullPath: '/meetings/'
      preLoaderRoute: typeof MeetingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings/$id': {
      id: '/meetings/$id'
      path: '/meetings/$id'
      fullPath: '/meetings/$id'
      preLoaderRoute: typeof MeetingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings/new': {
      id: '/meetings/new'
      path: '/meetings/new'
      fullPath: '/meetings/new'
      preLoaderRoute: typeof MeetingsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  TasksRoute: TasksRoute,
  MeetingsIdRoute: MeetingsIdRoute,
  MeetingsNewRoute: MeetingsNewRoute,
  MeetingsIndexRoute: MeetingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
